import {
  Margins,
  PageOrientation,
  PageSize,
  Alignment,
  Decoration,
  Column,
  PageBreak,
} from 'pdfmake/interfaces';
export var tableTm1_template = {
  headerRows: 10,
  //23 rows
  widths: [
    '4%',
    '30%',
    '6%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
    '3%',
  ],
  body: [
    //Table header
    [
      {
        text: `TM1-(1 July 2023)`,
        //   text: `TM1-${this.typeForm}(1 July 2023)`,
        style: ['txt_center'],
        colSpan: 23,
        alignment: 'right' as Alignment,
        border: [false, false, false, false],
      },
      {},
      {},
      {},

      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},

      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
    [
      {
        text: '',
        colSpan: 23,
        border: [false, false, false, false],
      },
      {},
      {},
      {},

      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},

      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
    // table info
    [
      {
        text: 'Report on THICKNESS MEASUREMENT of ALL DECK PLATING, ALL BOTTOM SHELL PLATING or SIDE SHELL PLATING',
        style: ['txt_center', 'fontS11'],
        colSpan: 23,
        decoration: 'underline' as Decoration,
        bold: true,
        border: [false, false, false, false],
      },
      {},
      {},
      {},

      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},

      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
    [
      {
        colSpan: 23,
        text: '',
        border: [false, false, false, false],
      },
      {},
      {},
      {},

      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},

      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
    [
      {
        text: "Ship's name:",
        alignment: 'center' as Alignment,
        colSpan: 2,
        border: [false, false, false, false],
      },
      {},
      {
        decoration: 'underline' as Decoration,
        text: 'M/T "TM THAI HA"',
        colSpan: 5,
        bold: true,
        border: [false, false, false, false],
      },
      {},
      {},
      {},
      {},
      {
        text: 'Class Identity No. ',
        colSpan: 3,
        border: [false, false, false, false],
      },
      {},
      {},
      {
        decoration: 'underline' as Decoration,
        text: '2312321',
        colSpan: 5,
        bold: true,
        border: [false, false, false, false],
      },
      {},
      {},
      {},
      {},

      {
        text: 'Report No. ',
        colSpan: 2,
        border: [false, false, false, false],
      },
      {},
      {
        decoration: 'underline' as Decoration,

        text: 'VMC.TUM 123',
        colSpan: 6,
        bold: true,
        border: [false, false, false, false],
      },

      {},
      {},
      {},
      {},
      {},
    ],
    [
      {
        colSpan: 23,
        text: '',
        border: [false, false, false, false],
      },
      {},
      {},
      {},

      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},

      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
    // table content
    [
      {
        text: 'STRAKE POSITION',
        alignment: 'left' as Alignment,
        colSpan: 2,
        style: 'txt_center',
      },
      {},
      { text: 'a', colSpan: 21, rowSpan: 1, bold: true },
      {},

      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},

      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
      {},
    ],
    [
      {
        style: 'txt_center',
        text: 'No.',
        rowSpan: 3,
      },
      {
        style: 'txt_center',
        text: 'PLATE POSITION',
        rowSpan: 3,
      },
      { style: 'txt_center', text: 'No. or Letter', rowSpan: 3 },
      { style: 'txt_center', text: 'Org.Thk.', rowSpan: 3 },
      { style: 'txt_center', text: 'Forward Reading', colSpan: 8 },
      {},
      {},
      {},
      {},
      {},
      {},
      {},

      { style: 'txt_center', text: 'Aft Reading', colSpan: 8 },
      {},
      {},
      {},
      {},
      {},
      {},
      {},

      {
        style: 'txt_center',
        text: 'Mean Dimunution (%)',
        colSpan: 2,
        rowSpan: 2,
      },
      {},

      { style: 'txt_center', text: 'Max Alwb Dim', rowSpan: 2 },
    ],
    [
      {},
      {},
      {},
      {},
      { text: 'Gauged (mm)', colSpan: 2, style: 'txt_center' },
      {},
      { text: 'Diminution P (mm)', colSpan: 3, style: 'txt_center' },
      {},
      {},
      { text: 'Diminution S (mm)', colSpan: 3, style: 'txt_center' },
      {},
      {},

      { text: 'Gauged (mm)', colSpan: 2, style: 'txt_center' },
      {},
      { text: 'Diminution P (mm)', colSpan: 3, style: 'txt_center' },
      {},
      {},
      { text: 'Diminution S (mm)', colSpan: 3, style: 'txt_center' },
      {},
      {},

      { text: '', colSpan: 2, style: 'txt_center' },

      {},
      { text: 'Max Alwb Dim' },
    ],
    [
      {},
      {},
      {},
      {},
      { text: 'P', style: 'txt_center' },
      { text: 'S', style: 'txt_center' },
      { text: 'mm', style: 'txt_center' },
      { text: '%', style: 'txt_center' },
      {},
      { text: 'mm', style: 'txt_center' },
      { text: '%', style: 'txt_center' },
      {},

      { text: 'P', style: 'txt_center' },
      { text: 'S', style: 'txt_center' },
      { text: 'mm', style: 'txt_center' },
      { text: '%', style: 'txt_center' },
      {},
      { text: 'mm', style: 'txt_center' },
      { text: '%', style: 'txt_center' },
      {},

      { text: 'P', style: 'txt_center' },
      { text: 'S', style: 'txt_center' },
      { text: 'mm', style: 'txt_center' },
    ],
  ],
};
